### ISSUE TITLE
Research and Activate linting for SCSS files

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-npm-tools#344]
For about a year now we've been getting reports and collecting thoughts on SCSS linting here and there. The goal of this issue is to work on an architecture that would allow us to start adding existing and custom lints.

Possible options from internal [IFI-956](https://issues.liferay.com/browse/IFI-956)
- [stylelint](https://stylelint.io/): [rules](https://stylelint.io/user-guide/rules)
- [sass-lint](https://github.com/sasstools/sass-lint): [rules](https://github.com/sasstools/sass-lint/tree/master/docs/rules)

The chosen linter should allow custom rules so we can tweak them when needed.

Existing related reading materials and requests:
- [x] [LPS-100754 Apply (S)CSS linting rules](https://issues.liferay.com/browse/LPS-100754)
- [x] [Lint for inappropriate use of SCSS/CSS import return values](https://github.com/liferay/eslint-config-liferay/issues/122) (done in https://github.com/liferay/eslint-config-liferay/pull/133)
- [ ] [z-index guidelines for DXP](https://github.com/liferay/liferay-frontend-guidelines/issues/104)
- [x] [Define the right name for CSS files](https://github.com/liferay/liferay-frontend-guidelines/issues/78) (https://github.com/liferay/liferay-npm-tools/pull/348) — this one marked as "done" insofar as we have a proof-of-concept PR up but still need to decide on actual conventions to enforce.
- [ ] [Define a CSS structure](https://github.com/liferay/liferay-frontend-guidelines/issues/77)
- [ ] [Sorting Imports](https://github.com/brianchandotcom/liferay-portal/pull/81633#issuecomment-561865490)
- [ ] [CSS format: Alert using BEM directive](https://github.com/liferay/liferay-npm-tools/issues/235)
- [ ] [CSS format: Alert if a variable not exist](https://github.com/liferay/liferay-npm-tools/issues/233)
- [x] [CSS format: Alert using /* comment */ ](https://github.com/liferay/liferay-npm-tools/issues/232) (done as part of https://github.com/liferay/liferay-npm-tools/pull/347)
- [ ] [CSS format: Disallow using !important](https://github.com/liferay/liferay-npm-tools/issues/231)
- [ ] [CSS format: ~Disallow~ Advice about using of shorthand](https://github.com/liferay/liferay-npm-tools/issues/221)
- [ ] [CSS format: Require uses of pseudo classes declared in this order: :hover, :focus, :active, :active:focus, :disabled](https://github.com/liferay/liferay-npm-tools/issues/220)
- [ ] [CSS format: Disallow using prefixes, use autoprefixer instead](https://github.com/liferay/liferay-npm-tools/issues/219)
- [ ] [CSS format: Disallow using of ID as a CSS selector](https://github.com/liferay/liferay-npm-tools/issues/218)
- [ ] [CSS format: Require SCSS files starting with "_" are being imported in some SCSS file](https://github.com/liferay/liferay-npm-tools/issues/217)

---

See also:

- Old stylelint config: https://github.com/liferay/liferay-frontend-source-formatter/blob/master/lib/config/stylelint.js
- Old custom rules: https://github.com/liferay/liferay-frontend-source-formatter/tree/master/lib/lint_css_rules

**Comment by wincent** [comment]
sass-lint has a scary warning now:

![sasstools_sass-lint__Pure_Node_js_Sass_linting](https://user-images.githubusercontent.com/7074/72613359-95576400-392f-11ea-8208-e2719c42b8c2.png)

stylelint, on the other hand, looks actively developed and popular; big dependency footprint though, but I can't really imagine any project that deals with SASS/CSS not having one...

**Comment by bryceosterhaus** [comment]
Would we be also using prettier to enforce formatting?

**Comment by jbalsas** [comment]
We already are :)

**Comment by wincent** [comment]
In terms of assessing viability of stylelint, did a quick test to see what happens when applying it to liferay-portal:

### Install in top-level modules folder

```
yarn add stylelint stylelint-config-standard -W --dev
````

This produces [this churn in the yarn.lock](https://gist.github.com/wincent/01e9ecb7fe342836c1b477d075ffc6f9) (about 849 lines added, 15 deleted).

After an `npx yarn-deduplicate yarn.lock`, the total effect is a bit less (815 lines added, 95 deleted) ([full diff here](https://gist.github.com/wincent/7ca505f34e5ceefad3138f4e25154e79)).

The increase in dependency footprint is unfortunate, but I can't see anything *obviously* egregious in the list (that's not to say that that there isn't something hiding though). It may be justified if we think the tool delivers enough compensating value.

### Run 

Create a top-level `.stylelintrc` file with these contents:

```
{
  "extends": "stylelint-config-standard"
}
```

And run it:

```
yarn run stylelint 'apps/**/*.scss*'
```

Takes about 2.5 minutes to run, and produces output-that-is-too-large-to-paste-into-a-gist-without-GitHub-returning-a-500-error (270k+ lines!). Many thousands of "errors", most of them apparently whitespace related.

Swapping in "stylelint-config-recommended" instead, we only get [47k lines of output](https://gist.github.com/wincent/706fd9a0c3c2837893e26b2ca9e354f0). With fewer rules active, the run seems much faster (less than 30 seconds). Note that in practice, we wouldn't do a whole-portal run like this but rather would run using the Node.js API only looking at the branch's changed files, so I think speed won't be a problem.

In terms of rules, in the recommended set most of the "errors" detected look to be just a question of config (unknown "at" rules), but it may also have detected some actual issues.

**Comment by wincent** [comment]
@marcoscv-work, @eduardoallegrini: just looping you in as discussed in the daily this morning — stylelint is one of the tools we're evaluating to give us some lint coverage in our SCSS files.

As noted in my previous comment, I checked to see that it works at all, how fast it runs, what it adds to our dependency footprint. Based on that extremely quick check, it looks like it could work.

Would you be able to take a look at [the rules list](https://stylelint.io/user-guide/rules) and nominate some rules which you think would be helpful to activate? Many rules are whitespace related and we should ignore all of those because we're already using Prettier to format our SCSS files; but among the others there may be something useful.

If you want a ticket to track this you could probably grab [LPS-100754](https://issues.liferay.com/browse/LPS-100754) ("Apply (S)CSS linting rules") and self-assign that.

**Comment by jbalsas** [comment]
Hey @wincent, is it possible that `yarn run stylelint 'apps/**/*.scss*'` is unnecessarily picking up folders like `build` or `build_node` or `classess` that can contain duplicated versions of the `.scss`?

**Comment by wincent** [comment]
Draft PR turning on stylelint is up at https://github.com/liferay/liferay-npm-tools/pull/347

I'll take it out of draft once we have an initial set of actual rules to turn on from @marcoscv-work  and @eduardoallegrini.

**Comment by eduardoallegrini** [comment]
I took a look at the list and here's what I consider useful:
## Possible errors
- color-no-invalid-hex
- font-family-no-duplicate-names
- function-calc-no-invalid
- unit-no-unknown
- property-no-unknown
- declaration-block-no-shorthand-property-overrides
- block-no-empty
- selector-pseudo-class-no-unknown
- selector-pseudo-element-no-unknown
- selector-type-no-unknown
- media-feature-name-no-unknown
- at-rule-no-unknown
- comment-no-empty
- no-duplicate-at-import-rules
- no-extra-semicolons
## Limit language features
- function-url-no-scheme-relative
- keyframes-name-pattern
- number-max-precision
- time-min-milliseconds
- shorthand-property-no-redundant-values
- value-no-vendor-prefix
- property-no-vendor-prefix
- declaration-no-important
- media-feature-name-no-vendor-prefix
- at-rule-no-vendor-prefix
- at-rule-property-requirelist
## Stylistic issues
- function-name-case
- function-url-quotes
- number-leading-zero (option: never)
- number-no-trailing-zeros
- string-quotes (option: double)
- length-zero-no-unit
- unit-case
- value-keyword-case (option: lower)
- property-case (option: lower)
## Extra
- color: launch a warning if you are not using a $variable as a value of the color property.
> use a Clay $variable https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/atlas/variables/_globals.scss or a function (lighten, darken) to get your color right http://scg.ar-ch.org/
- @media: launch a warning if you are using @media
> you should use @include media-break-point https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/bootstrap/mixins/_breakpoints.scss"

We could extend this point to all the existing mixing (e.g. text-truncate() or transition()) not sure but at-rule-blacklist from the list could help.

Another warning I'd like to have is
>using @media (max: something) instead @media (min: something) could lead to a not-mobile-first pattern

**Comment by wincent** [comment]
liferay-npm-scripts v20.0.0 is published and I am testing deploying it to liferay-portal here: https://github.com/wincent/liferay-portal/pull/122

If that looks good, will forward to Brian.

**Comment by wincent** [comment]
Ok, I think we've achieved the initial goal here, which was to provide infrastructure for linting SCSS. We have style-lint [active in liferay-portal](https://github.com/brianchandotcom/liferay-portal/pull/83654), and [something like 49 rules are turned on](https://github.com/liferay/liferay-npm-tools/blob/649f5d0b9d3af3dd003670d4b2e8411cb61a5dca/packages/liferay-npm-scripts/src/config/stylelint.json). Additionally, we have some [checking facilities that operate outside of ESLint/style-lint](https://github.com/liferay/liferay-npm-tools/blob/649f5d0b9d3af3dd003670d4b2e8411cb61a5dca/packages/liferay-npm-scripts/src/scripts/check/preflight.js) and [an example PR](https://github.com/liferay/liferay-npm-tools/pull/348) showing how we could use this to enforce file-naming conventions (draft status only  because we don't seem to have a consensus on what the file-naming conventions should actually be yet).

So, looking at the related issues in the initial checklist that we didn't get to, I think they can be divided into three categories:

### 1. Needing consensus

We need to reach an agreement on what the patterns should be before we undertake the technical work of actually enforcing them.

Examples:

- [Define a CSS structure](https://github.com/liferay/liferay-frontend-guidelines/issues/77) — consensus needed.
- [CSS format: Alert using BEM directive](https://github.com/liferay/liferay-npm-tools/issues/235) — consensus needed.
- [CSS format: Alert if a variable not exist](https://github.com/liferay/liferay-npm-tools/issues/233) — scope is unclear, which makes assessing technical feasibility difficult.
- [CSS format: ~Disallow~ Advice about using of shorthand](https://github.com/liferay/liferay-npm-tools/issues/221) — seems like we didn't get consensus and won't.
- [CSS format: Require uses of pseudo classes declared in this order: :hover, :focus, :active, :active:focus, :disabled](https://github.com/liferay/liferay-npm-tools/issues/220) — needs clarification due to contradictory examples.
- [CSS format: Disallow using of ID as a CSS selector](https://github.com/liferay/liferay-npm-tools/issues/218) — disagreement over whether this should be a hard error or warning (and if it is a warning, that means we can't use it, because in our build process only errors get surfaced to the developer).


### 2. Not viable

These are features which, while not impossible to implement, aren't realistically viable for one of the following reasons:

- Would involve a solution that is unlikely to be performant (for example, checks which would require us to traverse the repo looking for usage).
- Large impact without obvious autofix (for example, banning `!important`).
- Technical solution is unclear or needs a stronger proposal, so not immediately actionable in current state (for example, z-index guidelines).

Examples:

- [z-index guidelines for DXP](https://github.com/liferay/liferay-frontend-guidelines/issues/104) — needs proposal for action.
- [CSS format: Disallow using !important](https://github.com/liferay/liferay-npm-tools/issues/231) — extensively used in liferay-portal, no possibility of autofix, even manual fix may require big changes.
- [CSS format: Require SCSS files starting with "_" are being imported in some SCSS file](https://github.com/liferay/liferay-npm-tools/issues/217) — a useful rule, but requires a traversal (most lints/checks we have are file-local); it may be that a once-off (or periodic) maintenance script is a better fit for this kind of guideline.

### 3. Desirable, just didn't get to it yet

These are things which are well-defined, technically feasible, and for which we have consensus. An obvious example of this one is adopting autoprefixer and then linting against the use of unnecessary vendor prefixes.

Examples:

- [Sorting Imports](https://github.com/brianchandotcom/liferay-portal/pull/81633#issuecomment-561865490) — some risk here due to order-sensitivity of CSS, but we can provide escape hatches to avoid auto-sorting across "groups".
- [CSS format: Disallow using prefixes, use autoprefixer instead](https://github.com/liferay/liferay-npm-tools/issues/219) — seems viable, not too expensive, and highly beneficial; we should do it.

 ---

Next steps: I'm a going to close this issue, and then take appropriate action on the others according to the category that they are in. I'll label stuff that needs consensus still, close the not-viable ones as not-viable (or otherwise suggest an alternative course of action), and leave the desirable ones open and as-is.

**Comment by bryceosterhaus** [comment]
This is awesome, great job with this!
